name: windows

on: [push, pull_request]

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: BMRecord_Demo.sln
  SOLUTION_BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Creating project files
        shell: pwsh
        run: |
          ./GenerateProject.bat

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        shell: pwsh
        run: msbuild ${{env.SOLUTION_FILE_PATH}} -property:Configuration=${{env.SOLUTION_BUILD_TYPE}}