name: windows

on: [push, pull_request]

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: BMRecord_Demo.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Creating project files
        shell: pwsh
        run: |
          ./GenerateProject.bat

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2.297.0

      - name: Build
        shell: pwsh
        run: msbuild /m ${{env.SOLUTION_FILE_PATH}}